### ISSUE TITLE
Catch timeout error in Provider

### ISSUE THREAD

**Issue by christophehurpeau** [flagship-io/flagship-react-sdk#70]
Hello, 

We have a few errors on sentry due to flagship timeout.
It seems you don't catch the error to it throwed and don't leave us the option to handle it
Can you add catch when you fetch flags in the provider ?
- https://github.com/flagship-io/flagship-react-sdk/blob/f89665de880b7014880e498def5ab46c6bb2722d/src/FlagshipContext.tsx#L186
- https://github.com/flagship-io/flagship-react-sdk/blob/f89665de880b7014880e498def5ab46c6bb2722d/src/FlagshipContext.tsx#L279

with maybe a way to handle the error properly ? `onError` maybe ?
Thanks

**Comment by Madi-Ji** [comment]
Hey @christophehurpeau 

First, thanks for you investment and time you dedicated.
 
The team is looking into this and be back to you soon.

**Comment by guillaumejacquart** [comment]
Hey @christophehurpeau thanks for reporting this issue. Could you provide us with the sentry logs and the stack trace ? 
Also could you tell us the SDK version you're using (react-sdk and internal dependency js-sdk from the yarn or package lock files) ? 
The `fsVisitor.fetchFlags()` call internally call our JS SDK fetchFlags methods, which is wrapped around a try catch block: https://github.com/flagship-io/flagship-ts-sdk/blob/main/flagship/src/visitor/DefaultStrategy.ts#L269

**Comment by christophehurpeau** [comment]
Hello @guillaumejacquart

@flagship.io/react-sdk@2.1.5
@flagship.io/js-sdk@2.2.5

Sentry error: `timeout of 2000ms exceeded`

I'll share the stack on slack for confidentiality issues. Thanks !

**Comment by Heihokon** [comment]
This has just been fixed in [version 2.1.11](https://www.npmjs.com/package/@flagship.io/react-sdk/v/2.1.11)
See [change log](https://docs.developers.flagship.io/docs/react#fixed-1)

Thanks so much for the bug report!
